env:
    es6: true
    node: true
    browser: true

extends: 'airbnb-base'

parserOptions:
    ecmaVersion: 2018

rules:
    indent:
        - error
        - 4
    no-use-before-define: 0
    comma-dangle: 0
    no-param-reassign: 0
    no-plusplus: 0
    arrow-body-style: 0
    no-restricted-syntax: 0
    no-console: 0
    no-prompt: 0
    no-alert: 0

globals:
    kontra: true
    toFixed: true
    toRadians: true
    polarToCartesian: true
    Point: true
    AccessPoint: true
    accessPoints: true
    hash: true

overrides:
    -
        files: src/js/lib/*.js
        rules:
            no-unused-vars: off
