env:
    es6: true
    node: true
    browser: true

extends: 'airbnb-base'

parserOptions:
    ecmaVersion: 2018

rules:
    indent:
        - error
        - 4
    no-use-before-define: off
    comma-dangle: off
    no-param-reassign: off
    no-plusplus: off
    arrow-body-style: off
    no-restricted-syntax: off
    no-console: off
    no-prompt: off
    no-alert: off

globals:
    kontra: true
    toFixed: true
    toRadians: true
    polarToCartesian: true
    hash: true
    colorInGradient: true
    Point: true
    AccessPoint: true
    accessPoints: true

overrides:
    -
        files: src/js/lib/*.js
        rules:
            no-unused-vars: off
    -
        files: src/js/lib/util.js
        rules:
            no-bitwise: off
